name: Bonsai
on: pull_request
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: ['14', '12']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache "node_modules"
        uses: actions/cache@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          path: '**/node_modules'
          key: node_modules_${{ runner.os }}_${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile